// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/evax/app/data_sources/evax"
	repository2 "github.com/evax/app/services/tasks/repository"
	service2 "github.com/evax/app/services/tasks/service"
	"github.com/evax/app/services/users/repository"
	"github.com/evax/app/services/users/service"
)

// Injectors from wire.go:

func InitialiseApp() *AppImpl {
	dataSourceImpl := evax.NewEvaxDataSource()
	userRepositoryImpl := repository.NewUserRepository(dataSourceImpl)
	userServiceImpl := service.NewUserService(userRepositoryImpl)
	tasksRepositoryImpl := repository2.NewTaskRepository(dataSourceImpl)
	taskServiceImpl := service2.NewTaskService(tasksRepositoryImpl)
	appImpl := NewApp(userServiceImpl, taskServiceImpl)
	return appImpl
}
